//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторного создания кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference1
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IICUTech")]
    public interface IICUTech
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ICUTech.Intf-IICUTech#Login", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<ServiceReference1.LoginResponse> LoginAsync(ServiceReference1.LoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ICUTech.Intf-IICUTech#RegisterNewCustomer", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<ServiceReference1.RegisterNewCustomerResponse> RegisterNewCustomerAsync(ServiceReference1.RegisterNewCustomerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ICUTech.Intf-IICUTech#GetCustomerInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<ServiceReference1.GetCustomerInfoResponse> GetCustomerInfoAsync(ServiceReference1.GetCustomerInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ICUTech.Intf-IICUTech#UpdateCustomer", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<ServiceReference1.UpdateCustomerResponse> UpdateCustomerAsync(ServiceReference1.UpdateCustomerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ICUTech.Intf-IICUTech#GetVersion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<ServiceReference1.GetVersionResponse> GetVersionAsync(ServiceReference1.GetVersionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ICUTech.Intf-IICUTech#GetLocations", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<ServiceReference1.GetLocationsResponse> GetLocationsAsync(ServiceReference1.GetLocationsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ICUTech.Intf-IICUTech#GetCameras", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<ServiceReference1.GetCamerasResponse> GetCamerasAsync(ServiceReference1.GetCamerasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ICUTech.Intf-IICUTech#SetLocation", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<ServiceReference1.SetLocationResponse> SetLocationAsync(ServiceReference1.SetLocationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ICUTech.Intf-IICUTech#SetCamera", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<ServiceReference1.SetCameraResponse> SetCameraAsync(ServiceReference1.SetCameraRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ICUTech.Intf-IICUTech#SetAlarm", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<ServiceReference1.SetAlarmResponse> SetAlarmAsync(ServiceReference1.SetAlarmRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ICUTech.Intf-IICUTech#PushRegisterDevice", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<ServiceReference1.PushRegisterDeviceResponse> PushRegisterDeviceAsync(ServiceReference1.PushRegisterDeviceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ICUTech.Intf-IICUTech#PushMessage", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<ServiceReference1.PushMessageResponse> PushMessageAsync(ServiceReference1.PushMessageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ICUTech.Intf-IICUTech#SyncCameras", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<ServiceReference1.SyncCamerasResponse> SyncCamerasAsync(ServiceReference1.SyncCamerasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ICUTech.Intf-IICUTech#GetNotifications", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<ServiceReference1.GetNotificationsResponse> GetNotificationsAsync(ServiceReference1.GetNotificationsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ICUTech.Intf-IICUTech#GetNotificationsCount", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<ServiceReference1.GetNotificationsCountResponse> GetNotificationsCountAsync(ServiceReference1.GetNotificationsCountRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ICUTech.Intf-IICUTech#AddClip", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<ServiceReference1.AddClipResponse> AddClipAsync(ServiceReference1.AddClipRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ICUTech.Intf-IICUTech#GetClips", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<ServiceReference1.GetClipsResponse> GetClipsAsync(ServiceReference1.GetClipsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ICUTech.Intf-IICUTech#GetClipsCount", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<ServiceReference1.GetClipsCountResponse> GetClipsCountAsync(ServiceReference1.GetClipsCountRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ICUTech.Intf-IICUTech#DeleteNotification", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<ServiceReference1.DeleteNotificationResponse> DeleteNotificationAsync(ServiceReference1.DeleteNotificationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ICUTech.Intf-IICUTech#Encrypt", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<ServiceReference1.EncryptResponse> EncryptAsync(ServiceReference1.EncryptRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ICUTech.Intf-IICUTech#Crypt", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<ServiceReference1.CryptResponse> CryptAsync(ServiceReference1.CryptRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Login", WrapperNamespace="urn:ICUTech.Intf-IICUTech", IsWrapped=true)]
    public partial class LoginRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string UserName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string IPs;
        
        public LoginRequest()
        {
        }
        
        public LoginRequest(string UserName, string Password, string IPs)
        {
            this.UserName = UserName;
            this.Password = Password;
            this.IPs = IPs;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoginResponse", WrapperNamespace="urn:ICUTech.Intf-IICUTech", IsWrapped=true)]
    public partial class LoginResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public LoginResponse()
        {
        }
        
        public LoginResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RegisterNewCustomer", WrapperNamespace="urn:ICUTech.Intf-IICUTech", IsWrapped=true)]
    public partial class RegisterNewCustomerRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string Email;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string FirstName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string LastName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string Mobile;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public int CountryID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=6)]
        public int aID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=7)]
        public string SignupIP;
        
        public RegisterNewCustomerRequest()
        {
        }
        
        public RegisterNewCustomerRequest(string Email, string Password, string FirstName, string LastName, string Mobile, int CountryID, int aID, string SignupIP)
        {
            this.Email = Email;
            this.Password = Password;
            this.FirstName = FirstName;
            this.LastName = LastName;
            this.Mobile = Mobile;
            this.CountryID = CountryID;
            this.aID = aID;
            this.SignupIP = SignupIP;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RegisterNewCustomerResponse", WrapperNamespace="urn:ICUTech.Intf-IICUTech", IsWrapped=true)]
    public partial class RegisterNewCustomerResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public RegisterNewCustomerResponse()
        {
        }
        
        public RegisterNewCustomerResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCustomerInfo", WrapperNamespace="urn:ICUTech.Intf-IICUTech", IsWrapped=true)]
    public partial class GetCustomerInfoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int EntityID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string Username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string Password;
        
        public GetCustomerInfoRequest()
        {
        }
        
        public GetCustomerInfoRequest(int EntityID, string Username, string Password)
        {
            this.EntityID = EntityID;
            this.Username = Username;
            this.Password = Password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCustomerInfoResponse", WrapperNamespace="urn:ICUTech.Intf-IICUTech", IsWrapped=true)]
    public partial class GetCustomerInfoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public GetCustomerInfoResponse()
        {
        }
        
        public GetCustomerInfoResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateCustomer", WrapperNamespace="urn:ICUTech.Intf-IICUTech", IsWrapped=true)]
    public partial class UpdateCustomerRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int EntityID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string Username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string ValuesArray;
        
        public UpdateCustomerRequest()
        {
        }
        
        public UpdateCustomerRequest(int EntityID, string Username, string Password, string ValuesArray)
        {
            this.EntityID = EntityID;
            this.Username = Username;
            this.Password = Password;
            this.ValuesArray = ValuesArray;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateCustomerResponse", WrapperNamespace="urn:ICUTech.Intf-IICUTech", IsWrapped=true)]
    public partial class UpdateCustomerResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public UpdateCustomerResponse()
        {
        }
        
        public UpdateCustomerResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetVersion", WrapperNamespace="urn:ICUTech.Intf-IICUTech", IsWrapped=true)]
    public partial class GetVersionRequest
    {
        
        public GetVersionRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetVersionResponse", WrapperNamespace="urn:ICUTech.Intf-IICUTech", IsWrapped=true)]
    public partial class GetVersionResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public GetVersionResponse()
        {
        }
        
        public GetVersionResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetLocations", WrapperNamespace="urn:ICUTech.Intf-IICUTech", IsWrapped=true)]
    public partial class GetLocationsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int EntityID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string Username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string Password;
        
        public GetLocationsRequest()
        {
        }
        
        public GetLocationsRequest(int EntityID, string Username, string Password)
        {
            this.EntityID = EntityID;
            this.Username = Username;
            this.Password = Password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetLocationsResponse", WrapperNamespace="urn:ICUTech.Intf-IICUTech", IsWrapped=true)]
    public partial class GetLocationsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public GetLocationsResponse()
        {
        }
        
        public GetLocationsResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCameras", WrapperNamespace="urn:ICUTech.Intf-IICUTech", IsWrapped=true)]
    public partial class GetCamerasRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int EntityID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string Username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string Password;
        
        public GetCamerasRequest()
        {
        }
        
        public GetCamerasRequest(int EntityID, string Username, string Password)
        {
            this.EntityID = EntityID;
            this.Username = Username;
            this.Password = Password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCamerasResponse", WrapperNamespace="urn:ICUTech.Intf-IICUTech", IsWrapped=true)]
    public partial class GetCamerasResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public GetCamerasResponse()
        {
        }
        
        public GetCamerasResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetLocation", WrapperNamespace="urn:ICUTech.Intf-IICUTech", IsWrapped=true)]
    public partial class SetLocationRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int EntityID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string Username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string IP;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public int Port;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public int MediaPort;
        
        public SetLocationRequest()
        {
        }
        
        public SetLocationRequest(int EntityID, string Username, string Password, string IP, int Port, int MediaPort)
        {
            this.EntityID = EntityID;
            this.Username = Username;
            this.Password = Password;
            this.IP = IP;
            this.Port = Port;
            this.MediaPort = MediaPort;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetLocationResponse", WrapperNamespace="urn:ICUTech.Intf-IICUTech", IsWrapped=true)]
    public partial class SetLocationResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public SetLocationResponse()
        {
        }
        
        public SetLocationResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetCamera", WrapperNamespace="urn:ICUTech.Intf-IICUTech", IsWrapped=true)]
    public partial class SetCameraRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int EntityID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string Username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string LocationName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string URL;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public int CameraId;
        
        public SetCameraRequest()
        {
        }
        
        public SetCameraRequest(int EntityID, string Username, string Password, string LocationName, string URL, int CameraId)
        {
            this.EntityID = EntityID;
            this.Username = Username;
            this.Password = Password;
            this.LocationName = LocationName;
            this.URL = URL;
            this.CameraId = CameraId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetCameraResponse", WrapperNamespace="urn:ICUTech.Intf-IICUTech", IsWrapped=true)]
    public partial class SetCameraResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public SetCameraResponse()
        {
        }
        
        public SetCameraResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetAlarm", WrapperNamespace="urn:ICUTech.Intf-IICUTech", IsWrapped=true)]
    public partial class SetAlarmRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int EntityID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string Username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public int Status;
        
        public SetAlarmRequest()
        {
        }
        
        public SetAlarmRequest(int EntityID, string Username, string Password, int Status)
        {
            this.EntityID = EntityID;
            this.Username = Username;
            this.Password = Password;
            this.Status = Status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetAlarmResponse", WrapperNamespace="urn:ICUTech.Intf-IICUTech", IsWrapped=true)]
    public partial class SetAlarmResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public SetAlarmResponse()
        {
        }
        
        public SetAlarmResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PushRegisterDevice", WrapperNamespace="urn:ICUTech.Intf-IICUTech", IsWrapped=true)]
    public partial class PushRegisterDeviceRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int EntityID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string Username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string UDID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string DeviceID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public int TypeId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=6)]
        public bool AllowNotification;
        
        public PushRegisterDeviceRequest()
        {
        }
        
        public PushRegisterDeviceRequest(int EntityID, string Username, string Password, string UDID, string DeviceID, int TypeId, bool AllowNotification)
        {
            this.EntityID = EntityID;
            this.Username = Username;
            this.Password = Password;
            this.UDID = UDID;
            this.DeviceID = DeviceID;
            this.TypeId = TypeId;
            this.AllowNotification = AllowNotification;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PushRegisterDeviceResponse", WrapperNamespace="urn:ICUTech.Intf-IICUTech", IsWrapped=true)]
    public partial class PushRegisterDeviceResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public PushRegisterDeviceResponse()
        {
        }
        
        public PushRegisterDeviceResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PushMessage", WrapperNamespace="urn:ICUTech.Intf-IICUTech", IsWrapped=true)]
    public partial class PushMessageRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int EntityID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string Username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string text;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string FunctionPassword;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public int KindType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=6)]
        public int KindID;
        
        public PushMessageRequest()
        {
        }
        
        public PushMessageRequest(int EntityID, string Username, string Password, string text, string FunctionPassword, int KindType, int KindID)
        {
            this.EntityID = EntityID;
            this.Username = Username;
            this.Password = Password;
            this.text = text;
            this.FunctionPassword = FunctionPassword;
            this.KindType = KindType;
            this.KindID = KindID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PushMessageResponse", WrapperNamespace="urn:ICUTech.Intf-IICUTech", IsWrapped=true)]
    public partial class PushMessageResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public PushMessageResponse()
        {
        }
        
        public PushMessageResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SyncCameras", WrapperNamespace="urn:ICUTech.Intf-IICUTech", IsWrapped=true)]
    public partial class SyncCamerasRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int EntityID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string Username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public int CamerasCount;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public int[] CameraIds;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public string[] CameraNames;
        
        public SyncCamerasRequest()
        {
        }
        
        public SyncCamerasRequest(int EntityID, string Username, string Password, int CamerasCount, int[] CameraIds, string[] CameraNames)
        {
            this.EntityID = EntityID;
            this.Username = Username;
            this.Password = Password;
            this.CamerasCount = CamerasCount;
            this.CameraIds = CameraIds;
            this.CameraNames = CameraNames;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SyncCamerasResponse", WrapperNamespace="urn:ICUTech.Intf-IICUTech", IsWrapped=true)]
    public partial class SyncCamerasResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public SyncCamerasResponse()
        {
        }
        
        public SyncCamerasResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetNotifications", WrapperNamespace="urn:ICUTech.Intf-IICUTech", IsWrapped=true)]
    public partial class GetNotificationsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int EntityID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string Username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string UDID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public int ResultType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public int LimitFrom;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=6)]
        public int LimitTo;
        
        public GetNotificationsRequest()
        {
        }
        
        public GetNotificationsRequest(int EntityID, string Username, string Password, string UDID, int ResultType, int LimitFrom, int LimitTo)
        {
            this.EntityID = EntityID;
            this.Username = Username;
            this.Password = Password;
            this.UDID = UDID;
            this.ResultType = ResultType;
            this.LimitFrom = LimitFrom;
            this.LimitTo = LimitTo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetNotificationsResponse", WrapperNamespace="urn:ICUTech.Intf-IICUTech", IsWrapped=true)]
    public partial class GetNotificationsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public GetNotificationsResponse()
        {
        }
        
        public GetNotificationsResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetNotificationsCount", WrapperNamespace="urn:ICUTech.Intf-IICUTech", IsWrapped=true)]
    public partial class GetNotificationsCountRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int EntityID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string Username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string UDID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public int ResultType;
        
        public GetNotificationsCountRequest()
        {
        }
        
        public GetNotificationsCountRequest(int EntityID, string Username, string Password, string UDID, int ResultType)
        {
            this.EntityID = EntityID;
            this.Username = Username;
            this.Password = Password;
            this.UDID = UDID;
            this.ResultType = ResultType;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetNotificationsCountResponse", WrapperNamespace="urn:ICUTech.Intf-IICUTech", IsWrapped=true)]
    public partial class GetNotificationsCountResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public GetNotificationsCountResponse()
        {
        }
        
        public GetNotificationsCountResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddClip", WrapperNamespace="urn:ICUTech.Intf-IICUTech", IsWrapped=true)]
    public partial class AddClipRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int EntityId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string UserName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public int cameraID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public int clipID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public int ClipLength;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=6)]
        public string ClipDate;
        
        public AddClipRequest()
        {
        }
        
        public AddClipRequest(int EntityId, string UserName, string Password, int cameraID, int clipID, int ClipLength, string ClipDate)
        {
            this.EntityId = EntityId;
            this.UserName = UserName;
            this.Password = Password;
            this.cameraID = cameraID;
            this.clipID = clipID;
            this.ClipLength = ClipLength;
            this.ClipDate = ClipDate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddClipResponse", WrapperNamespace="urn:ICUTech.Intf-IICUTech", IsWrapped=true)]
    public partial class AddClipResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public AddClipResponse()
        {
        }
        
        public AddClipResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetClips", WrapperNamespace="urn:ICUTech.Intf-IICUTech", IsWrapped=true)]
    public partial class GetClipsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int EntityId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string UserName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public int ResultType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public int cameraID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public string DateFrom;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=6)]
        public string DateTo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=7)]
        public int LimitFrom;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=8)]
        public int LimitTo;
        
        public GetClipsRequest()
        {
        }
        
        public GetClipsRequest(int EntityId, string UserName, string Password, int ResultType, int cameraID, string DateFrom, string DateTo, int LimitFrom, int LimitTo)
        {
            this.EntityId = EntityId;
            this.UserName = UserName;
            this.Password = Password;
            this.ResultType = ResultType;
            this.cameraID = cameraID;
            this.DateFrom = DateFrom;
            this.DateTo = DateTo;
            this.LimitFrom = LimitFrom;
            this.LimitTo = LimitTo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetClipsResponse", WrapperNamespace="urn:ICUTech.Intf-IICUTech", IsWrapped=true)]
    public partial class GetClipsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public GetClipsResponse()
        {
        }
        
        public GetClipsResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetClipsCount", WrapperNamespace="urn:ICUTech.Intf-IICUTech", IsWrapped=true)]
    public partial class GetClipsCountRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int EntityId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string UserName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public int ResultType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public int cameraID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public string DateFrom;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=6)]
        public string DateTo;
        
        public GetClipsCountRequest()
        {
        }
        
        public GetClipsCountRequest(int EntityId, string UserName, string Password, int ResultType, int cameraID, string DateFrom, string DateTo)
        {
            this.EntityId = EntityId;
            this.UserName = UserName;
            this.Password = Password;
            this.ResultType = ResultType;
            this.cameraID = cameraID;
            this.DateFrom = DateFrom;
            this.DateTo = DateTo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetClipsCountResponse", WrapperNamespace="urn:ICUTech.Intf-IICUTech", IsWrapped=true)]
    public partial class GetClipsCountResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public GetClipsCountResponse()
        {
        }
        
        public GetClipsCountResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteNotification", WrapperNamespace="urn:ICUTech.Intf-IICUTech", IsWrapped=true)]
    public partial class DeleteNotificationRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int EntityID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string Username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public int NotificationID;
        
        public DeleteNotificationRequest()
        {
        }
        
        public DeleteNotificationRequest(int EntityID, string Username, string Password, int NotificationID)
        {
            this.EntityID = EntityID;
            this.Username = Username;
            this.Password = Password;
            this.NotificationID = NotificationID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteNotificationResponse", WrapperNamespace="urn:ICUTech.Intf-IICUTech", IsWrapped=true)]
    public partial class DeleteNotificationResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public DeleteNotificationResponse()
        {
        }
        
        public DeleteNotificationResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Encrypt", WrapperNamespace="urn:ICUTech.Intf-IICUTech", IsWrapped=true)]
    public partial class EncryptRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string DataString;
        
        public EncryptRequest()
        {
        }
        
        public EncryptRequest(string DataString)
        {
            this.DataString = DataString;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EncryptResponse", WrapperNamespace="urn:ICUTech.Intf-IICUTech", IsWrapped=true)]
    public partial class EncryptResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public EncryptResponse()
        {
        }
        
        public EncryptResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Crypt", WrapperNamespace="urn:ICUTech.Intf-IICUTech", IsWrapped=true)]
    public partial class CryptRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int EntityId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string UserName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string FuncPassword;
        
        public CryptRequest()
        {
        }
        
        public CryptRequest(int EntityId, string UserName, string Password, string FuncPassword)
        {
            this.EntityId = EntityId;
            this.UserName = UserName;
            this.Password = Password;
            this.FuncPassword = FuncPassword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CryptResponse", WrapperNamespace="urn:ICUTech.Intf-IICUTech", IsWrapped=true)]
    public partial class CryptResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public CryptResponse()
        {
        }
        
        public CryptResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface IICUTechChannel : ServiceReference1.IICUTech, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class ICUTechClient : System.ServiceModel.ClientBase<ServiceReference1.IICUTech>, ServiceReference1.IICUTech
    {
        
        /// <summary>
        /// Реализуйте этот разделяемый метод для настройки конечной точки службы.
        /// </summary>
        /// <param name="serviceEndpoint">Настраиваемая конечная точка</param>
        /// <param name="clientCredentials">Учетные данные клиента.</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ICUTechClient() : 
                base(ICUTechClient.GetDefaultBinding(), ICUTechClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.IICUTechPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ICUTechClient(EndpointConfiguration endpointConfiguration) : 
                base(ICUTechClient.GetBindingForEndpoint(endpointConfiguration), ICUTechClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ICUTechClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ICUTechClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ICUTechClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ICUTechClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ICUTechClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.LoginResponse> LoginAsync(ServiceReference1.LoginRequest request)
        {
            return base.Channel.LoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.RegisterNewCustomerResponse> RegisterNewCustomerAsync(ServiceReference1.RegisterNewCustomerRequest request)
        {
            return base.Channel.RegisterNewCustomerAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.GetCustomerInfoResponse> GetCustomerInfoAsync(ServiceReference1.GetCustomerInfoRequest request)
        {
            return base.Channel.GetCustomerInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.UpdateCustomerResponse> UpdateCustomerAsync(ServiceReference1.UpdateCustomerRequest request)
        {
            return base.Channel.UpdateCustomerAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.GetVersionResponse> GetVersionAsync(ServiceReference1.GetVersionRequest request)
        {
            return base.Channel.GetVersionAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.GetLocationsResponse> GetLocationsAsync(ServiceReference1.GetLocationsRequest request)
        {
            return base.Channel.GetLocationsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.GetCamerasResponse> GetCamerasAsync(ServiceReference1.GetCamerasRequest request)
        {
            return base.Channel.GetCamerasAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.SetLocationResponse> SetLocationAsync(ServiceReference1.SetLocationRequest request)
        {
            return base.Channel.SetLocationAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.SetCameraResponse> SetCameraAsync(ServiceReference1.SetCameraRequest request)
        {
            return base.Channel.SetCameraAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.SetAlarmResponse> SetAlarmAsync(ServiceReference1.SetAlarmRequest request)
        {
            return base.Channel.SetAlarmAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.PushRegisterDeviceResponse> PushRegisterDeviceAsync(ServiceReference1.PushRegisterDeviceRequest request)
        {
            return base.Channel.PushRegisterDeviceAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.PushMessageResponse> PushMessageAsync(ServiceReference1.PushMessageRequest request)
        {
            return base.Channel.PushMessageAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.SyncCamerasResponse> SyncCamerasAsync(ServiceReference1.SyncCamerasRequest request)
        {
            return base.Channel.SyncCamerasAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.GetNotificationsResponse> GetNotificationsAsync(ServiceReference1.GetNotificationsRequest request)
        {
            return base.Channel.GetNotificationsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.GetNotificationsCountResponse> GetNotificationsCountAsync(ServiceReference1.GetNotificationsCountRequest request)
        {
            return base.Channel.GetNotificationsCountAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.AddClipResponse> AddClipAsync(ServiceReference1.AddClipRequest request)
        {
            return base.Channel.AddClipAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.GetClipsResponse> GetClipsAsync(ServiceReference1.GetClipsRequest request)
        {
            return base.Channel.GetClipsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.GetClipsCountResponse> GetClipsCountAsync(ServiceReference1.GetClipsCountRequest request)
        {
            return base.Channel.GetClipsCountAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.DeleteNotificationResponse> DeleteNotificationAsync(ServiceReference1.DeleteNotificationRequest request)
        {
            return base.Channel.DeleteNotificationAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.EncryptResponse> EncryptAsync(ServiceReference1.EncryptRequest request)
        {
            return base.Channel.EncryptAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.CryptResponse> CryptAsync(ServiceReference1.CryptRequest request)
        {
            return base.Channel.CryptAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.IICUTechPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Не удалось найти конечную точку с именем \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.IICUTechPort))
            {
                return new System.ServiceModel.EndpointAddress("http://isapi.icu-tech.com/icutech-test.dll/soap/IICUTech");
            }
            throw new System.InvalidOperationException(string.Format("Не удалось найти конечную точку с именем \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ICUTechClient.GetBindingForEndpoint(EndpointConfiguration.IICUTechPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ICUTechClient.GetEndpointAddress(EndpointConfiguration.IICUTechPort);
        }
        
        public enum EndpointConfiguration
        {
            
            IICUTechPort,
        }
    }
}
